name: MIN
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - krb5=1.21.2
  - libffi=3.4.2
  - libpq=16.2
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - openssl=3.3.0
  - pip=24.0
  - psycopg2=2.9.9
  - python=3.10.14
  - python_abi=3.10
  - setuptools=69.5.1
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
