version: '3'
services:
  db:
    build: ./DataBase
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: project
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - final_project_network

  app:
    build: ./Code
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always
    networks:
      - final_project_network

volumes:
  db_data:

networks:
  final_project_network:
    driver: bridge
